package: action_kit_api
generate:
  models: true
  embedded-spec: true
output-options:
  skip-prune: true
  exclude-schemas:
    - ParameterOption
    - Widget
    - LineChartWidgetGroupMatcher
    - ExecutionModification
additional-imports:
  - package: "github.com/google/uuid"
